### ISSUE TITLE
Bug: Potential Memory Leak Issue

### ISSUE THREAD

**Issue by rpf13** [rpf13/sportsshooting_react#48]
while testing, I figured the following error:

![Image](https://github.com/rpf13/sportsshooting_react/assets/25194462/0ea29785-d3ab-4b4b-94f0-a878faa95eea)

Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function. at PopularMatches (https://3000-rpf13-sportsshootingre-1ivdp0otp5o.ws-eu104.gitpod.io/static/js/main.chunk.js:9070:3) at div at https://3000-rpf13-sportsshootingre-1ivdp0otp5o.ws-eu104.gitpod.io/static/js/vendors~main.chunk.js:13317:23 at div at https://3000-rpf13-sportsshootingre-1ivdp0otp5o.ws-eu104.gitpod.io/static/js/vendors~main.chunk.js:17213:23 at GunsPage (https://3000-rpf13-sportsshootingre-1ivdp0otp5o.ws-eu104.gitpod.io/static/js/main.chunk.js:6322:3)

**Comment by rpf13** [comment]
It seems that the app is trying to update the state of the component, even though it has already been unmounted, causing the error.
So I have implemented a "mounted" flag to check if it is still mounted or not, hence preventing an update, if it is not mounted anymore.

Here the adjusted useEffect code of the PopularMatches.js component:

```jsx
  useEffect(() => {
    // check if component is mounted
    let isMounted = true;

    const handleMount = async () => {
      try {
        const { data } = await axiosReq.get(
          "/matches/?ordering=-attendings_count"
        );
        // if component is still mounted, update data
        if (isMounted) {
          setMatchData((prevState) => ({
            ...prevState,
            popularMatches: data,
          }));
        }
      } catch {
        handleError();
      }
    };
    handleMount();

    // cleanup when the component is unmounted, update variable
    return () => {
      isMounted = false;
    };
  }, [handleError]);
```

commit id: e2d6e00
